// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEIGmr2FjL5Q-ba4GTgiIwowalyqJX7Tk',
    appId: '1:68077147180:web:54aea91ab2f66985a46d89',
    messagingSenderId: '68077147180',
    projectId: 'flashchat-f48a7',
    authDomain: 'flashchat-f48a7.firebaseapp.com',
    storageBucket: 'flashchat-f48a7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWpRzsirjGnY0j_gY15YrvFJTxCDj8pik',
    appId: '1:68077147180:android:00c9f949cf5612e2a46d89',
    messagingSenderId: '68077147180',
    projectId: 'flashchat-f48a7',
    storageBucket: 'flashchat-f48a7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRZrk1pDqgZa3GVWIuH46kr1FAaf7bVV0',
    appId: '1:68077147180:ios:af127523001287d5a46d89',
    messagingSenderId: '68077147180',
    projectId: 'flashchat-f48a7',
    storageBucket: 'flashchat-f48a7.appspot.com',
    iosBundleId: 'com.example.flashchatApp.RunnerTests',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRZrk1pDqgZa3GVWIuH46kr1FAaf7bVV0',
    appId: '1:68077147180:ios:b7fe6ac4ed77b636a46d89',
    messagingSenderId: '68077147180',
    projectId: 'flashchat-f48a7',
    storageBucket: 'flashchat-f48a7.appspot.com',
    iosBundleId: 'com.example.flashchatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEIGmr2FjL5Q-ba4GTgiIwowalyqJX7Tk',
    appId: '1:68077147180:web:95a273a5f98b4548a46d89',
    messagingSenderId: '68077147180',
    projectId: 'flashchat-f48a7',
    authDomain: 'flashchat-f48a7.firebaseapp.com',
    storageBucket: 'flashchat-f48a7.appspot.com',
  );

}